spring:
  cloud:
    gateway:
      routes:
      - id: service-hi
        uri: lb://SERVICE-HI
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          
          https://blog.csdn.net/zhuyu19911016520/article/details/86562615